# -*- coding: utf-8 -*-
"""Sample_Containers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KjyLbbNL6FzsG-mf4KNwLwoFmy7tailp
"""

import numpy as np
import pandas as pd
from collections import deque


num_entries = 1000  # You can specify the number of entries as per your requirement

# Generate random values for Image_Container (assuming you have a list of image containers)
image_containers = ['Container_' + str(i) for i in range(1, num_entries + 1)]

# Generate random values for Payload Size in GB
payload_size = np.random.uniform(200, 90.4 * 1000, num_entries) / 1000  # Convert MB to GB

# Generate random values for number_of_sharing_points
sharing_points = np.random.randint(85308, 200987, num_entries)

# Generate random values for number_of_updates
updates = np.random.randint(1, 26, num_entries)

# Combine all data into a dataframe
data = pd.DataFrame({
    'Image_Container': image_containers,
    'Payload(gb)': payload_size,
    'Sharing_Points': sharing_points,
    'Num_Updates': updates
})

# Save to a CSV file
data.to_csv("random_data.csv", index=False)

# Print the first few rows for verification
print(data)